'use client';

import React, { useState, useEffect } from 'react';
import { Leaf, Waves, Home, BarChart3, ShieldAlert, Settings, Download, Loader2 } from 'lucide-react';
import { motion, useMotionValue, animate } from 'framer-motion';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface SidebarProps {
    analysisData?: Record<string, unknown> | null;
    currentYear?: number;
    selectedVillage?: string | null;
    onVillageSelect?: (name: string | null) => void;
}

const Counter = ({ value, prefix = "" }: { value: number; label?: string; prefix?: string }) => {
    const count = useMotionValue(0);
    const [displayValue, setDisplayValue] = useState(prefix + "0.0");

    useEffect(() => {
        const controls = animate(count, value, {
            duration: 2,
            ease: "easeOut",
            onUpdate: (latest) => {
                setDisplayValue(prefix + latest.toLocaleString(undefined, {
                    minimumFractionDigits: 1,
                    maximumFractionDigits: 1
                }));
            }
        });
        return controls.stop;
    }, [value, prefix, count]);

    return <span>{displayValue}</span>;
};

const Sidebar = ({ analysisData, currentYear = 2022, selectedVillage, onVillageSelect }: SidebarProps) => {
    const [isDownloading, setIsDownloading] = useState(false);

    const generateReport = async () => {
        if (isDownloading) return;
        setIsDownloading(true);

        try {
            const doc = new jsPDF('p', 'mm', 'a4');
            const pageWidth = doc.internal.pageSize.getWidth();
            
            // 1. Header with Logo & Title
            doc.setFillColor(2, 6, 23); // slate-950
            doc.rect(0, 0, pageWidth, 40, 'F');
            
            doc.setTextColor(16, 185, 129); // emerald-500
            doc.setFontSize(22);
            doc.setFont('helvetica', 'bold');
            doc.text('Sundarbans Sentinel', 20, 20);
            
            doc.setTextColor(148, 163, 184); // slate-400
            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            doc.text('Ecosystem Monitoring & Impact Report', 20, 28);
            
            doc.setTextColor(255, 255, 255);
            doc.text(`Observation Year: ${currentYear}`, pageWidth - 60, 20);
            
            // 2. Stats Section
            let y = 60;
            doc.setTextColor(15, 23, 42); // slate-900
            doc.setFontSize(16);
            doc.text('Environmental Status', 20, y);
            y += 15;
            
            const carbonValue = analysisData?.total_carbon_emitted || 2400;
            const erosionValue = analysisData?.hectares_lost || 158.4;
            
            doc.setFontSize(12);
            doc.setTextColor(100, 116, 139); // slate-500
            doc.text('Carbon Loss:', 20, y);
            doc.setTextColor(15, 23, 42);
            doc.text(`${carbonValue.toFixed(1)} Tons`, 60, y);
            
            y += 10;
            doc.setTextColor(100, 116, 139);
            doc.text('Erosion Rate:', 20, y);
            doc.setTextColor(248, 113, 113); // red-400
            doc.text(`${erosionValue.toFixed(1)} Hectares (Critical)`, 60, y);
            
            // 3. Village Vulnerability
            y += 25;
            doc.setTextColor(15, 23, 42);
            doc.setFontSize(16);
            doc.text('Village Vulnerability Assessment', 20, y);
            y += 15;
            
            const villages = [
                { name: 'Satkhira', risk: 'High', color: [248, 113, 113] },
                { name: 'Gosaba', risk: 'Moderate', color: [251, 146, 60] },
                { name: 'Kultali', risk: 'Low', color: [74, 222, 128] },
            ];
            
            villages.forEach(v => {
                doc.setFontSize(12);
                doc.setTextColor(15, 23, 42);
                doc.text(v.name, 30, y);
                
                doc.setFillColor(v.color[0], v.color[1], v.color[2]);
                doc.rect( pageWidth - 50, y - 4, 30, 6, 'F');
                doc.setTextColor(255, 255, 255);
                doc.setFontSize(8);
                doc.text(v.risk, pageWidth - 40, y);
                
                y += 12;
            });
            
            // 4. Footer
            doc.setDrawColor(226, 232, 240); // slate-200
            doc.line(20, 270, pageWidth - 20, 270);
            doc.setTextColor(148, 163, 184);
            doc.setFontSize(8);
            doc.text('Generated by Sundarbans Sentinel Dashboard • AI-Powered Conservation', pageWidth / 2, 280, { align: 'center' });
            
            doc.save(`Sundarbans_Report_${currentYear}.pdf`);
        } catch (error) {
            console.error('PDF generation error:', error);
        } finally {
            setIsDownloading(false);
        }
    };

    const carbonValue = analysisData?.total_carbon_emitted || 2400;
    const erosionValue = analysisData?.hectares_lost || 158.4;

    return (
        <div className="w-80 h-screen bg-slate-950 text-slate-200 flex flex-col border-r border-slate-800 z-10 relative">
            <div className="p-6 border-b border-slate-800">
                <h1 className="text-xl font-bold bg-gradient-to-r from-emerald-400 to-cyan-400 bg-clip-text text-transparent">
                    Sundarbans Sentinel
                </h1>
                <p className="text-xs text-slate-500 mt-1">Ecosystem Monitoring Dashboard</p>
            </div>

            <div className="flex-1 overflow-y-auto p-4 space-y-8">
                {/* Carbon Loss Section */}
                <section>
                    <div className="flex items-center gap-2 mb-4 px-2">
                        <Leaf className="w-5 h-5 text-emerald-500" />
                        <h2 className="text-sm font-semibold uppercase tracking-wider text-slate-400">Carbon Loss (Tons)</h2>
                    </div>
                    <div className="bg-slate-900/50 rounded-xl p-4 border border-slate-800">
                        <div className="flex justify-between items-end">
                            <div>
                                <p className="text-2xl font-bold text-white">
                                    <Counter value={carbonValue} label="carbon" />
                                </p>
                                <p className="text-xs text-emerald-400 mt-1">↑ 12% vs last year</p>
                            </div>
                            <BarChart3 className="w-10 h-10 text-slate-700" />
                        </div>
                        <div className="mt-4 h-1.5 w-full bg-slate-800 rounded-full overflow-hidden">
                            <motion.div
                                initial={{ width: 0 }}
                                animate={{ width: '65%' }}
                                className="h-full bg-emerald-500"
                            />
                        </div>
                    </div>
                </section>

                {/* Erosion Rate Section */}
                <section>
                    <div className="flex items-center gap-2 mb-4 px-2">
                        <Waves className="w-5 h-5 text-cyan-500" />
                        <h2 className="text-sm font-semibold uppercase tracking-wider text-slate-400">Erosion Rate (Hectares)</h2>
                    </div>
                    <div className="bg-slate-900/50 rounded-xl p-4 border border-slate-800">
                        <div className="flex justify-between items-end">
                            <div>
                                <p className="text-2xl font-bold text-white">
                                    <Counter value={erosionValue} label="erosion" />
                                </p>
                                <p className="text-xs text-red-400 mt-1">Critical status</p>
                            </div>
                            <Waves className="w-10 h-10 text-slate-700" />
                        </div>
                        <div className="mt-4 grid grid-cols-5 gap-1">
                            {[1, 2, 3, 4, 5].map((i) => (
                                <div key={i} className={`h-8 rounded-sm ${i < 4 ? 'bg-cyan-500/60' : 'bg-slate-800'}`} />
                            ))}
                        </div>
                    </div>
                </section>

                {/* Village Vulnerability Section */}
                <section>
                    <div className="flex items-center gap-2 mb-4 px-2">
                        <ShieldAlert className="w-5 h-5 text-amber-500" />
                        <h2 className="text-sm font-semibold uppercase tracking-wider text-slate-400">Village Vulnerability</h2>
                    </div>
                    <div className="space-y-3">
                        {[
                            { name: 'Satkhira', risk: 'High', color: 'text-red-400' },
                            { name: 'Gosaba', risk: 'Moderate', color: 'text-amber-400' },
                            { name: 'Kultali', risk: 'Low', color: 'text-emerald-400' },
                        ].map((village) => (
                            <button
                                key={village.name}
                                onClick={() => onVillageSelect?.(selectedVillage === village.name ? null : village.name)}
                                className={`w-full flex items-center justify-between p-3 rounded-lg border transition-all ${
                                    selectedVillage === village.name
                                        ? 'bg-slate-800 border-emerald-500/50 shadow-[0_0_15px_rgba(16,185,129,0.1)]'
                                        : 'bg-slate-900/50 border-slate-800 hover:border-slate-700'
                                }`}
                            >
                                <div className="flex items-center gap-3">
                                    <Home className={`w-4 h-4 ${selectedVillage === village.name ? 'text-emerald-400' : 'text-slate-500'}`} />
                                    <span className={`text-sm font-medium ${selectedVillage === village.name ? 'text-white' : 'text-slate-300'}`}>
                                        {village.name}
                                    </span>
                                </div>
                                <span className={`text-xs font-bold ${village.color}`}>{village.risk}</span>
                            </button>
                        ))}
                    </div>
                </section>

                {/* Download Section */}
                <section className="px-2">
                    <button
                        onClick={generateReport}
                        disabled={isDownloading}
                        className="w-full bg-emerald-500 hover:bg-emerald-600 disabled:bg-emerald-800 disabled:cursor-not-allowed text-white font-bold py-3 px-4 rounded-xl transition-all shadow-lg flex items-center justify-center gap-2 group"
                    >
                        {isDownloading ? (
                            <Loader2 className="w-5 h-5 animate-spin" />
                        ) : (
                            <Download className="w-5 h-5 group-hover:translate-y-0.5 transition-transform" />
                        )}
                        <span>{isDownloading ? 'Baking Report...' : 'Download PDF Report'}</span>
                    </button>
                </section>
            </div>

            <div className="p-4 border-t border-slate-800">
                <button className="flex items-center gap-3 w-full p-3 hover:bg-slate-900 rounded-lg transition-colors text-slate-400 hover:text-white">
                    <Settings className="w-5 h-5" />
                    <span className="text-sm font-medium">Settings</span>
                </button>
            </div>
        </div>
    );
};

export default Sidebar;
